import React from 'react';
import UserNode from './UserNode.jsx';

const config = {
  automaticRearrangeAfterDropNode: true,
  collapsible: true,
  directed: true,
  focusAnimationDuration: 0.75,
  focusZoom: 1,
  height: 400,
  highlightDegree: 2,
  highlightOpacity: 0.2,
  linkHighlightBehavior: true,
  maxZoom: 12,
  minZoom: 0.05,
  nodeHighlightBehavior: true,
  panAndZoom: false,
  staticGraph: false,
  staticGraphWithDragAndDrop: false,
  width: 800,
  d3: {
    alphaTarget: 0.05,
    gravity: -250,
    linkLength: 120,
    linkStrength: 2,
    disableLinkForce: false,
  },
  node: {
    color: '#d3d3d3',
    fontColor: 'black',
    fontSize: 10,
    fontWeight: 'normal',
    highlightColor: 'red',
    highlightFontSize: 14,
    highlightFontWeight: 'bold',
    highlightStrokeColor: 'red',
    highlightStrokeWidth: 1.5,
    mouseCursor: 'crosshair',
    opacity: 0.9,
    renderLabel: true,
    size: 200,
    strokeColor: 'none',
    strokeWidth: 1.5,
    svg: '',
    symbolType: 'circle',
    viewGenerator: (node) => <UserNode node={node} />,
  },
  link: {
    color: 'lightgray',
    fontColor: 'black',
    fontSize: 8,
    fontWeight: 'normal',
    highlightColor: 'red',
    highlightFontSize: 8,
    highlightFontWeight: 'normal',
    labelProperty: 'label',
    mouseCursor: 'pointer',
    opacity: 1,
    renderLabel: false,
    semanticStrokeWidth: true,
    strokeWidth: 3,
    markerHeight: 6,
    markerWidth: 6,
  },
};

// const config = {
//   automaticRearrangeAfterDropNode: false,
//   collapsible: false,
//   height: 400,
//   highlightDegree: 1,
//   highlightOpacity: 0.2,
//   linkHighlightBehavior: true,
//   maxZoom: 8,
//   minZoom: 0.1,
//   nodeHighlightBehavior: true,
//   panAndZoom: false,
//   staticGraph: false,
//   width: 800,
//   node: {
//     color: '#d3d3d3',
//     fontColor: 'black',
//     fontSize: 12,
//     fontWeight: 'normal',
//     highlightColor: 'red',
//     highlightFontSize: 12,
//     highlightFontWeight: 'bold',
//     highlightStrokeColor: 'SAME',
//     highlightStrokeWidth: 1.5,
//     labelProperty: 'name',
//     mouseCursor: 'pointer',
//     opacity: 1,
//     renderLabel: false,
//     size: {
//       width: 700,
//       height: 900,
//     },
//     strokeColor: 'none',
//     strokeWidth: 1,
//     svg: '',
//     symbolType: 'circle',
//     viewGenerator: (node) => <UserNode node={node} />,
//   },
//   link: {
//     color: '#d3d3d3',
//     opacity: 1,
//     semanticStrokeWidth: false,
//     strokeWidth: 4,
//     highlightColor: 'blue',
//   },
// };

export { config };
