MATCH (a)
DETACH DELETE a;

CREATE CONSTRAINT IF NOT EXISTS ON (p:Anime) ASSERT p.title IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS ON (p:Anime) ASSERT EXISTS(p.rank);
// CREATE INDEX ON :Anime(title);
// CREATE INDEX ON :Anime(tank);